# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c7bb41db90a689f84fcd82501908d1ce57529e7f6cdd5fe511bc8d4c8ab8efb967200b5bd7f6caf65c75b39fedd8091967df7ddd458800e157c2590519a4436

test:
  secret_key_base: 7b4f24565d38d06fff7cdfaf89f8182b83e50e55a1820255a2789c2959ee44dfe87a1cd0b7cdbbfd781dffababac93340a7f995f6a6b5ff273df602b5f4a8797

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
